{% set name = "brake" %}
{% set version = "1.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  git_url: https://github.com/cmshobe/brake-model

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - numpy
    - scipy
    - ruamel.yaml
    - basic-modeling-interface

build:
  number: 1
  script: python setup.py install --single-version-externally-managed --record record.txt

test:
  imports:
    - brake

about:
  home: http://csdms.colorado.edu/wiki/Model:BRaKE
  license: MIT
  summary: BRaKE is the Blocky River and Knickpoint Evolution model
  dev_url: https://github.com/cmshobe/brake-model
