language: generic
os:
- linux
- osx
env:
  global:
  - CONDA_PREFIX=$HOME/miniconda
  - MINICONDA_URL_BASE="https://repo.continuum.io/miniconda/Miniconda2-latest"
  - TRAVIS_PYTHON_VERSION="2.7"
  - secure: "soCESiqWpXBNB7WfMhYXYRfwSX30DkOlQWqfSnY/7jQT82CzZQxyyzLuauupQ/KF1VtUNln4neD3nYAE3K3/PiXs983qP5BKC/rrkO0BOFXIB0SlJXnsWrUI/aINtYeAAds+SJW0AvKzH8S4NXtxqJzyrpVG29CEj+NqN6ze3ZTNdhOH20lVdfThEreUe46l9AY9L8XSqgWfOwZU+mXfuQP5e0s7Y19c7/gx1mHphgpklnEnw/apgu1qKa3LDppDQpMjWx4y+HeH5R6ehJlEBBq3IgMAsRjKSFkooJeJmAN/buafwNT0z7ez+0mADGTP0tz1F67sXGu4cKw2iRDMiI8zO7k+KUvLI82cJ0YecN2y/bFk2B/deYl0qaafLs+O3nGGQvMp721+GH6x6kz8xuG0yXvPOtabyZ7hRVn6vudkJyuErJVWudx7ua+jpmxTpC6Yw3D6ii0Q6pCGYd81rDpkWHafcksznPbHHpi7Xll5A+ijp2+oXu52aY2Awf7p1VDnJwSOfGh6df6QZBXp66AaJV+UwUPUsTFq8qka1qb3oVlN/y0aSK7LfjM1JButG+VV/PcOz+yUtbujoDABnO4gZ6nUJbx9WBzZakoULvUkUyGUWza6NxuM1DS1rabgZZ+SVqmp60VJRba7Qm3omKWSriErJvfCoN7VOCVImcg="
sudo: false
before_install:
- |
  if [[ $TRAVIS_OS_NAME == "osx" ]]; then
    brew remove --force $(brew list)
    brew cleanup -s
    rm -rf $(brew --cache)
  fi
install:
- |
  if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
    OS="MacOSX-x86_64"
  else
    OS="Linux-x86_64"
  fi
- curl $MINICONDA_URL_BASE-$OS.sh > $HOME/miniconda.sh
- bash $HOME/miniconda.sh -b -p $CONDA_PREFIX
- export PATH="$CONDA_PREFIX/bin:$PATH"
- hash -r
- conda config --set always_yes yes --set changeps1 no
- conda install python=$TRAVIS_PYTHON_VERSION
- conda install -q conda-build anaconda-client coverage sphinx
script:
- conda build ./recipe -c csdms-stack -c defaults -c conda-forge --old-build-string
after_success:
- |
  if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
    curl https://raw.githubusercontent.com/csdms/ci-tools/master/anaconda_upload.py > $HOME/anaconda_upload.py
    echo $ANACONDA_TOKEN | python $HOME/anaconda_upload.py ./recipe --channel=main --org=csdms-stack --old-build-string --token=-
  fi
